---
title: "Logistic Regression"
author: "Rose Ellison"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caTools)
#install.packages("ElemStatLearn")
library(ElemStatLearn)

```

# Logistic Regression
```{r}
# Reda the data
data <- read.csv("Social_Network_Ads.csv")
data <- data[ , 3:5]


# Splitting the data
set.seed(1)
split <- sample.split(data$Purchased, SplitRatio = .75)
training <- subset(data, split == TRUE)
test <- subset(data, split == FALSE)

# Feature Scaling
training[ , 1:2] <- scale(training[ , 1:2])
test[ , 1:2] <- scale(test[ , 1:2])

# Fitting Logistic Regression to the training set
classifier <- glm(Purchased~., 
                  family = binomial, 
                  data = training)

# Predicting the test set results
prob_pred <- predict(classifier, 
                     type = 'response', 
                     newdata = test[-3])
y_pred <- ifelse(prob_pred > 0.5, 1, 0)

# Making the Confusion Matrix
cm <- table(test[ , 3], y_pred)


# Visualizing the data
set = training
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
prob_set = predict(classifier, type = 'response', newdata = grid_set)
y_grid = ifelse(prob_set > 0.5, 1, 0)
plot(set[, -3],
     main = 'Logistic Regression (Training set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))


# Visualising the Test set results
set = test
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
prob_set = predict(classifier, type = 'response', newdata = grid_set)
y_grid = ifelse(prob_set > 0.5, 1, 0)
plot(set[, -3],
     main = 'Logistic Regression (Test set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))
```

