---
title: "SimpleLinearRegression"
author: "Rose Ellison"
date: "1/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caTools)
library(ggplot2)
```

# Simple Linear Regression
- Is there a correlation between experience and salary?
- Is there a linear dependency?

```{r}
# Set seed
set.seed(1)

# Importting salary data
salary <- read.csv('../data/Salary_Data.csv')

# Splitting the dataset into the training set and test set
split <- sample.split(salary$Salary, SplitRatio = 2/3)
training.set <- subset(salary, split == TRUE)
test.set <- subset(salary, split == FALSE)

# Fitting simple linear regression to the training set
regressor <- lm(formula = Salary ~ YearsExperience,
                data = training.set)

# Predicting the test set results
y.pred <- predict(regressor, newdata = test.set)

# Visualizing the training set results
ggplot() + 
  geom_point(aes(x = training.set$YearsExperience, y = training.set$Salary), col = 'lightblue', lw = 4) + 
  geom_line(aes(x = training.set$YearsExperience, y = predict(regressor, newdata = training.set)), col = 'darkblue') + 
  theme_bw() + 
  ggtitle('Salary VS Experience (Training Set)') + 
  xlab('Years of Experience') + 
  ylab('Salary')

```




```{r}
# Visualizing the test set results
ggplot() + 
  geom_point(aes(x = test.set$YearsExperience, y = test.set$Salary), col = 'lightblue', lw = 4) + 
  geom_line(aes(x = training.set$YearsExperience, y = predict(regressor, newdata = training.set)), col = 'darkblue') + 
  theme_bw() + 
  ggtitle('Salary VS Experience (Test Set)') + 
  xlab('Years of Experience') + 
  ylab('Salary')
```
# Conclusion
- 

